#!/bin/bash
#PBS -l ncpus=5
#PBS -l mem=5GB
#PBS -q normal
#PBS -P fo27
#PBS -l walltime=00:05:00
#PBS -l storage=gdata/fo27+scratch/tn81+scratch/fo27
#PBS -l wd

module load nci-parallel/1.0.0a
 
export ncores_per_task=1
export ncores_per_numanode=12
 

echo "Running on $(hostname)"
echo "Running on $(date)"
echo "Current directory is $(pwd)"
echo "This job is allocated the following CPUs:"
echo $(cat $PBS_NODEFILE)
echo "Total number of allocated CPUs is $PBS_NCPUS"
echo "Total number of allocated nodes is $PBS_NUM_NODES"
echo "Total number of cores per node is $PBS_NUM_PPN"
echo "Total number of cores per task is $ncores_per_task"
echo "Total number of cores per NUMA node is $ncores_per_numanode"


mpirun -np $((PBS_NCPUS/ncores_per_task)) --map-by ppr:$((ncores_per_numanode/ncores_per_task)):NUMA:PE=${ncores_per_task} nci-parallel --input-file cmds.txt --timeout 4000