#!/bin/bash
###############################################################################################################
#                                            BatchArtemisSRAMiner                                             #
#                                                JCO Mifsud                                                   #
#                                                   2024                                                      #
###############################################################################################################

#PBS -N kraken
#PBS -l select=1:ncpus=12:mem=120GB
#PBS -l walltime=84:00:00

# Load Kraken module
module load kraken2/2.1.1 || {
    echo "Error: Failed to load kraken module."
    exit 1
}

# Read in list of file names or accessions
readarray -t myarray <"$file_of_accessions"
export library_run=${myarray["$PBS_ARRAY_INDEX"]}
library_run_without_path="$(basename -- $library_run)"
library_id=$(echo $library_run_without_path | sed 's/\\.fastq.gz//g' | sed 's/_*//g')

# Setting variables
wd=/project/"$root_project"/"$project"/kraken
inpath=/scratch/"$root_project"/"$project"/raw_reads
outpath=/project/"$root_project"/"$project"/kraken
threads=10
db=/scratch/VELAB/Databases/kraken_db/

if [ ! -d "$wd" ]; then
    mkdir -p "$wd"
fi

cd "$wd" || {
    echo "Error: Cannot change directory to $wd"
    exit 1
}

# Execute Kraken
kraken2 --db $db --paired "$inpath"/"$library_id"_1.fastq.gz "$inpath"/"$library_id"_2.fastq.gz \
    --output "$outpath"/"$library_id"_kraken_output \
    --report "$outpath"/"$library_id"_kraken_report \
    --gzip-compressed \
    --use-names \
    --memory-mapping \
    --report-minimizer-data \
    --minimum-hit-groups 3 \
    --threads $threads || {
    echo "Error: Failed to execute Kraken."
    exit 1
}
